### ISSUE TITLE
Does not work for Phantom 4 Advanced

### ISSUE THREAD

**Issue by hy9be** [DJI-Mobile-SDK-Tutorials/iOS-PlaybackDemo#4] opened 2017-07-19 21:15 UTC
It runs into error first and I changed the code according to https://github.com/DJI-Mobile-SDK-Tutorials/iOS-PlaybackDemo/issues/1. The error is gone now. But nothing happens when I click on "Multi Prev" button. Any ideas?

**Comment by hy9be** [comment] 2017-07-19 21:28
I see in the header file:
![image](https://user-images.githubusercontent.com/3392907/28390306-7503cdbc-6ca7-11e7-9704-5db77e7ea9ab.png)

As in the document it is said:
![image](https://user-images.githubusercontent.com/3392907/28390350-aba65a60-6ca7-11e7-8817-43d2445c32e4.png)

Does it mean I cannot multi-preview the images on Phantom 4 Advanced or Pro?

**Comment by oliverou** [comment] 2017-07-20 03:56
Hi @hy9be , as the documentation said, Phantom 4 Advanced and Pro don't support Playback mode, so this PlaybackDemo will not work on both of them. Please use MediaDownload instead, you can check this tutorial to learn how to use MediaDownload: <http://developer.dji.com/mobile-sdk/documentation/ios-tutorials/PanoDemo.html#using-media-download-mode>

**Comment by oliverou** [comment] 2017-12-19 13:22
Since the issue is resolved, close it now. If you need any help, please feel free to reopen this issue.

**Closed as completed by oliverou** 2017-12-19 13:22 UTC
